# Site settings
title: Mostly Trub
email: james@jagrieve.com
description: "Misadventures in homebrewing and fermentation in Singapore."
baseurl: ""
url: "http://beer.jagrieve.com"
twitter_username: jamesagrieve
github_username:  jagrieve
excerpt_separator: "----"

# Build settings
markdown: kramdown
permalink: /blog/:title
